#ifndef ENGINE_COMMON_H
#define	ENGINE_COMMON_H

#define COLOR_TEXTURE_UNIT              GL_TEXTURE0
#define COLOR_TEXTURE_UNIT_INDEX        0
#define SHADOW_TEXTURE_UNIT             GL_TEXTURE1
#define SHADOW_TEXTURE_UNIT_INDEX       1

#endif	/* ENGINE_COMMON_H */

